AllCops:
  TargetRubyVersion: 2.5.7
  Exclude:
    - 'Gemfile'
Layout/LineLength:
  Max: 100
  Exclude:
    - 'db/seeds/*'
  IgnoredPatterns: ['\A#']
Metrics/BlockLength:
  Exclude:
    - 'apps/*/application.rb'
    - 'db/migrations/*'
    - 'lib/tasks/*.rb'
    - 'Rakefile'
    - 'spec/**/*.rb'
    - 'config/init/*.rb'
Metrics/MethodLength:
  Max: 30
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/BlockParameterName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Style/Alias:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/LambdaCall:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/OptionalArguments:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
