source 'https://rubygems.org'
gem 'discordrb'
gem 'dry-validation'
gem 'dotenv'
gem 'faker', :git => 'https://github.com/faker-ruby/faker.git', :branch => 'master'
gem 'i18n'
gem 'pg'
gem 'puma'
gem 'rubocop'
gem 'sequel'
#gem 'sequel_postgresql_triggers'
