# Table: combats
# Columns:
#  id         | bigint  | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  combatants | text    |
#  complete   | boolean | NOT NULL DEFAULT false
# Indexes:
#  combats_pkey | PRIMARY KEY btree (id)

require 'sequel'
require_relative '../config/init/configure_sequel'

class Combat < Sequel::Model
end
