# Table: monsters
# Columns:
#  id          | bigint                      | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  attack      | integer                     | NOT NULL
#  xp_awarded  | integer                     | NOT NULL
#  attack_roll | text                        |
#  race        | text                        | NOT NULL
#  stat_id     | bigint                      |
#  created_at  | timestamp without time zone | NOT NULL DEFAULT '2020-08-16 23:43:00.129233'::timestamp without time zone
#  updated_at  | timestamp without time zone | NOT NULL DEFAULT '2020-08-16 23:43:00.129235'::timestamp without time zone
# Indexes:
#  monsters_pkey             | PRIMARY KEY btree (id)
#  index_monsters_on_stat_id | btree (stat_id)

require 'sequel'
require_relative '../config/init/configure_sequel'

class Monster < Sequel::Model
  many_to_one :stat
end
