# Table: stats
# Columns:
#  id           | bigint                      | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  armor_class  | integer                     |
#  action       | integer                     | NOT NULL DEFAULT 1
#  bonus_action | integer                     | NOT NULL DEFAULT 1
#  charisma     | integer                     | NOT NULL
#  constitution | integer                     | NOT NULL
#  dexterity    | integer                     | NOT NULL
#  experience   | integer                     | NOT NULL DEFAULT 0
#  hp           | integer                     | NOT NULL
#  hp_max       | integer                     | NOT NULL
#  intelligence | integer                     | NOT NULL
#  level        | integer                     | NOT NULL DEFAULT 1
#  failure      | integer                     | NOT NULL DEFAULT 0
#  success      | integer                     | NOT NULL DEFAULT 0
#  strength     | integer                     | NOT NULL
#  wisdom       | integer                     | NOT NULL
#  status       | text                        |
#  alive        | boolean                     | NOT NULL DEFAULT true
#  unconscious  | boolean                     | NOT NULL DEFAULT false
#  created_at   | timestamp without time zone | NOT NULL DEFAULT '2020-08-16 23:43:00.140437'::timestamp without time zone
#  updated_at   | timestamp without time zone | NOT NULL DEFAULT '2020-08-16 23:43:00.140439'::timestamp without time zone
# Indexes:
#  stats_pkey | PRIMARY KEY btree (id)

require 'sequel'
require_relative '../config/init/configure_sequel'

class Stat < Sequel::Model
  one_to_one :monster
  one_to_one :player
end
