# Table: weapons
# Columns:
#  id          | bigint                      | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name        | text                        |
#  weapon_type | text                        |
#  cost        | text                        |
#  damage      | text                        |
#  damage_type | text                        |
#  range       | text                        |
#  weight      | text                        |
#  properties  | text                        |
#  created_at  | timestamp without time zone | NOT NULL DEFAULT '2020-08-16 23:43:00.143519'::timestamp without time zone
#  updated_at  | timestamp without time zone | NOT NULL DEFAULT '2020-08-16 23:43:00.143521'::timestamp without time zone
# Indexes:
#  weapons_pkey | PRIMARY KEY btree (id)

require 'sequel'
require_relative '../config/init/configure_sequel'

Sequel::Model.plugin :dirty
Sequel.extension :core_extensions
Sequel.extension :core_refinements
Sequel.extension :migration
Sequel.extension :pg_array
Sequel.extension :pg_array_ops
Sequel.extension :error_sql

Sequel::Model.plugin :association_pks
Sequel::Model.plugin :boolean_readers
Sequel::Model.plugin :many_through_many

using Sequel::CoreRefinements

class Weapon < Sequel::Model
  one_to_one :player
end
